// BytePlus ModelArk client — Seedream 4.5 (image) and Seedance 2.0 (video).
// ModelArk is ByteDance's official API. It trusts face-containing outputs
// generated by Seedream models, so Seedream-generated avatars can be used as
// reference images for Seedance 2.0 without the untrusted-domain content
// filter that fal.ai's Seedance proxy applies to real-person photos.
//
// Required env: ARK_API_KEY, ARK_BASE_URL
//   e.g. ARK_BASE_URL=https://ark.ap-southeast.bytepluses.com/api/v3

const SEEDREAM_MODEL = 'seedream-4-5-250828'
const SEEDANCE_MODEL = 'dreamina-seedance-2-0-260128'

const RETRY_DELAYS_MS = [1000, 3000, 8000]

// Default base URL used when ARK_BASE_URL isn't set — also used by
// uploadToByteplusFiles so callers can pass a relative `/avatars/...` path
// without explicitly providing the base.
const DEFAULT_BASE_URL = 'https://ark.ap-southeast.bytepluses.com/api/v3'

function getConfig() {
  const apiKey = process.env.ARK_API_KEY || ''
  const baseUrl = (process.env.ARK_BASE_URL || '').replace(/\/+$/, '')
  if (!apiKey || !baseUrl) {
    throw new Error('ARK_API_KEY and ARK_BASE_URL must be set')
  }
  return { apiKey, baseUrl }
}

export function isByteplusConfigured() {
  return !!(process.env.ARK_API_KEY && process.env.ARK_BASE_URL)
}

async function postJson(url, apiKey, body) {
  const res = await fetch(url, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${apiKey}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(body)
  })
  const text = await res.text()
  let data
  try { data = JSON.parse(text) } catch { data = { raw: text } }
  return { ok: res.ok, status: res.status, data, text }
}

async function getJson(url, apiKey) {
  const res = await fetch(url, {
    method: 'GET',
    headers: { 'Authorization': `Bearer ${apiKey}` }
  })
  const text = await res.text()
  let data
  try { data = JSON.parse(text) } catch { data = { raw: text } }
  return { ok: res.ok, status: res.status, data, text }
}

// uploadToByteplusFiles — resolves any image input to a URL that the
// BytePlus Seedance/Seedream APIs accept as `image_url`.
//
// Input can be:
//   - "https://..." or "http://..."   → returned as-is. BytePlus accepts
//                                        any public URL (no fal-style
//                                        untrusted-domain filter).
//   - "/avatars/avatar-1.jpg"          → resolved against NEXT_PUBLIC_BASE_URL
//                                        (or opts.baseUrl) to an absolute https URL.
//   - "data:image/...;base64,..."      → uploaded to BytePlus Files API. On any
//                                        failure (network/4xx/5xx), the original
//                                        data: URL is returned — BytePlus's
//                                        OpenAI-compatible image_url accepts
//                                        data URIs inline, so this still works
//                                        end-to-end.
//
// Returns a string. Throws only on truly invalid input (null/empty/non-string).
export async function uploadToByteplusFiles(input, opts = {}) {
  if (!input || typeof input !== 'string') {
    throw new Error('uploadToByteplusFiles: input must be a non-empty string')
  }

  // Already an absolute URL — BytePlus trusts public URLs, pass through.
  if (input.startsWith('http://') || input.startsWith('https://')) {
    return input
  }

  // Relative path — resolve to absolute https URL using app base.
  if (input.startsWith('/')) {
    const base =
      opts.baseUrl ||
      process.env.NEXT_PUBLIC_BASE_URL ||
      'https://ugc-studi-production.up.railway.app'
    const resolved = `${base.replace(/\/+$/, '')}${input}`
    return resolved
  }

  // data: URL — try the BytePlus Files API. On any failure, fall back to
  // returning the data URI — BytePlus image_url accepts inline base64.
  if (input.startsWith('data:')) {
    const apiKey = process.env.ARK_API_KEY || ''
    if (!apiKey) {
      console.warn('[uploadToByteplusFiles] ARK_API_KEY not set — returning data URL inline')
      return input
    }
    const baseUrl = ((process.env.ARK_BASE_URL || DEFAULT_BASE_URL)).replace(/\/+$/, '')
    const url = `${baseUrl}/files`
    try {
      const m = input.match(/^data:([^;]+);base64,(.+)$/)
      if (!m) throw new Error('malformed data URL')
      const mime = m[1] || 'image/jpeg'
      const ext = mime.split('/')[1] || 'jpg'
      const buf = Buffer.from(m[2], 'base64')
      const blob = new Blob([buf], { type: mime })
      const fd = new FormData()
      fd.append('file', blob, `upload-${Date.now()}.${ext}`)
      // OpenAI-compatible "purpose" — BytePlus accepts vendor-specific values.
      // "batch" works on the OpenAI Files API and is a safe generic value.
      fd.append('purpose', opts.purpose || 'batch')

      const res = await fetch(url, {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${apiKey}` },
        body: fd
      })
      const text = await res.text()
      let data
      try { data = JSON.parse(text) } catch { data = { raw: text } }
      if (!res.ok) {
        console.warn(`[uploadToByteplusFiles] HTTP ${res.status} — falling back to data URL: ${text.slice(0, 200)}`)
        return input
      }
      // BytePlus Files API may return either a direct public URL field or an
      // OpenAI-style file id. Prefer URL; fall back to id-based content URL.
      const directUrl = data?.url || data?.data?.url || data?.public_url || data?.uri
      if (directUrl && typeof directUrl === 'string' && directUrl.startsWith('http')) {
        console.log(`[uploadToByteplusFiles] uploaded → ${directUrl.slice(0, 80)}`)
        return directUrl
      }
      const fileId = data?.id || data?.data?.id || data?.file_id
      if (fileId) {
        // OpenAI-convention retrieval URL. BytePlus Seedance may not be able
        // to fetch this without auth, but we surface it for diagnostics and
        // fall through to data URL below as a safer default.
        console.warn(`[uploadToByteplusFiles] got file id ${fileId} but no public URL — falling back to data URL`)
      } else {
        console.warn('[uploadToByteplusFiles] response missing url and id — falling back to data URL:', text.slice(0, 200))
      }
      return input
    } catch (e) {
      console.warn(`[uploadToByteplusFiles] upload threw — falling back to data URL: ${e.message}`)
      return input
    }
  }

  // Anything else — return as-is and let the caller fail loudly if Seedance rejects it.
  return input
}

// generateImage — Seedream 4.5 text-to-image.
// Returns { url } on success.
export async function generateImage(prompt, opts = {}) {
  const { apiKey, baseUrl } = getConfig()
  const url = `${baseUrl}/images/generations`
  const body = {
    model: opts.model || SEEDREAM_MODEL,
    prompt,
    size: opts.size || '1024x1024',
    response_format: 'url'
  }

  let lastErr
  for (let attempt = 0; attempt < RETRY_DELAYS_MS.length + 1; attempt++) {
    try {
      console.log(`[BytePlus] Seedream request (attempt ${attempt + 1}):`, {
        url, model: body.model, promptPreview: prompt.slice(0, 80)
      })
      const { ok, status, data, text } = await postJson(url, apiKey, body)
      if (ok) {
        const imgUrl = data?.data?.[0]?.url || data?.images?.[0]?.url || data?.url
        if (imgUrl) {
          console.log(`[BytePlus] Seedream OK: ${imgUrl.slice(0, 80)}...`)
          return { url: imgUrl }
        }
        console.error('[BytePlus] Seedream OK but no url in response:', text.slice(0, 300))
        lastErr = new Error('Seedream returned no image url')
      } else {
        console.error(`[BytePlus] Seedream failed ${status}: ${text.slice(0, 300)}`)
        lastErr = new Error(`Seedream HTTP ${status}: ${text.slice(0, 200)}`)
        if (status >= 400 && status < 500 && status !== 429) break
      }
    } catch (e) {
      console.error(`[BytePlus] Seedream exception (attempt ${attempt + 1}):`, e.message)
      lastErr = e
    }
    const delay = RETRY_DELAYS_MS[attempt]
    if (delay) await new Promise(r => setTimeout(r, delay))
  }
  throw lastErr || new Error('Seedream failed after retries')
}

// generateVideo — Seedance 2.0 async task: create → poll → return video url.
// imageUrls: array of public URLs to use as reference frames (first one is the
// primary frame; pass an empty array for pure text-to-video).
// Returns { videoUrl }.
export async function generateVideo({ prompt, imageUrls = [], duration = 5, model } = {}) {
  const { apiKey, baseUrl } = getConfig()
  const tasksUrl = `${baseUrl}/contents/generations/tasks`

  const content = [{ type: 'text', text: prompt }]
  for (const u of imageUrls) {
    if (!u) continue
    content.push({ type: 'image_url', image_url: { url: u }, role: 'reference_image' })
  }

  const body = {
    model: model || SEEDANCE_MODEL,
    content
  }

  // Create task with retries.
  let taskId
  let lastErr
  for (let attempt = 0; attempt < RETRY_DELAYS_MS.length + 1; attempt++) {
    try {
      console.log(`[BytePlus] Seedance create task (attempt ${attempt + 1}):`, {
        url: tasksUrl,
        model: body.model,
        promptPreview: prompt.slice(0, 80),
        refImages: imageUrls.filter(Boolean).length,
        duration
      })
      const { ok, status, data, text } = await postJson(tasksUrl, apiKey, body)
      if (ok) {
        taskId = data?.id || data?.task_id || data?.data?.id
        if (taskId) {
          console.log(`[BytePlus] Seedance task created: ${taskId}`)
          break
        }
        console.error('[BytePlus] Seedance create OK but no task id:', text.slice(0, 300))
        lastErr = new Error('Seedance create returned no task id')
      } else {
        console.error(`[BytePlus] Seedance create failed ${status}: ${text.slice(0, 300)}`)
        lastErr = new Error(`Seedance create HTTP ${status}: ${text.slice(0, 200)}`)
        if (status >= 400 && status < 500 && status !== 429) break
      }
    } catch (e) {
      console.error(`[BytePlus] Seedance create exception:`, e.message)
      lastErr = e
    }
    const delay = RETRY_DELAYS_MS[attempt]
    if (delay) await new Promise(r => setTimeout(r, delay))
  }
  if (!taskId) throw lastErr || new Error('Seedance task creation failed')

  // Poll status — every 5s, up to 300s (60 polls).
  const pollUrl = `${baseUrl}/contents/generations/tasks/${encodeURIComponent(taskId)}`
  const TIMEOUT_MS = 300_000
  const POLL_INTERVAL_MS = 5_000
  const start = Date.now()

  while (Date.now() - start < TIMEOUT_MS) {
    await new Promise(r => setTimeout(r, POLL_INTERVAL_MS))
    try {
      const { ok, status, data, text } = await getJson(pollUrl, apiKey)
      if (!ok) {
        console.error(`[BytePlus] Seedance poll failed ${status}: ${text.slice(0, 200)}`)
        continue
      }
      const taskStatus = (data?.status || data?.task_status || data?.data?.status || '').toLowerCase()
      const videoUrl =
        data?.content?.video_url ||
        data?.video?.url ||
        data?.video_url ||
        data?.output?.video_url ||
        data?.data?.video_url
      console.log(`[BytePlus] Seedance poll ${taskId}: status=${taskStatus || 'unknown'}${videoUrl ? ', has video url' : ''}`)
      if (taskStatus === 'succeeded' || taskStatus === 'success' || videoUrl) {
        if (videoUrl) return { videoUrl }
        console.error('[BytePlus] Seedance succeeded but no video url:', text.slice(0, 300))
        throw new Error('Seedance succeeded but returned no video url')
      }
      if (taskStatus === 'failed' || taskStatus === 'cancelled' || taskStatus === 'canceled') {
        const reason = data?.error?.message || data?.failure_reason || text.slice(0, 200)
        throw new Error(`Seedance task ${taskStatus}: ${reason}`)
      }
    } catch (e) {
      console.error(`[BytePlus] Seedance poll exception:`, e.message)
      if (/Seedance task (failed|cancelled|canceled)/.test(e.message) ||
          /Seedance succeeded but returned no video url/.test(e.message)) {
        throw e
      }
    }
  }
  throw new Error(`Seedance task ${taskId} timed out after ${Math.round(TIMEOUT_MS / 1000)}s`)
}
